#!../framework/bin/python

from game_card import *

#mazzo
Deck = []
Deck.append( Game_Card(1941, "Japanese Attack Pearl Harbor", 0) )
Deck.append( Game_Card(1942, "Anne Frank Goes Into Hiding", 1) )
Deck.append( Game_Card(1942, "Manhattan Project Begins", 2) )
Deck.append( Game_Card(1945, "Hitler Commits Suicide", 3) )
Deck.append( Game_Card(1945, "U.S. Drops Atomic Bombs on Hiroshima and Nagasaki", 5) )
Deck.append( Game_Card(1946, "The Nuremberg Trials", 4) )
Deck.append( Game_Card(1948, "Gandhi Assassinated", 6) )
Deck.append( Game_Card(1949, "NATO Established", 7) )
Deck.append( Game_Card(1950, "Color TV Introduced", 8) )
Deck.append( Game_Card(1953, "DNA Discovered", 9) )
Deck.append( Game_Card(1958, "NASA Founded", 10) )
Deck.append( Game_Card(1959, "Castro Becomes Dictator of Cuba", 11) )
Deck.append( Game_Card(1961, "Berlin Wall Built", 12) )
Deck.append( Game_Card(1962, "Marilyn Monroe Found Dead", 13) )
Deck.append( Game_Card(1964, "Beatles Become Popular in U.S.", 14) )
Deck.append( Game_Card(1965, "U.S. Sends Troops to Vietnam", 15) )
Deck.append( Game_Card(1969, "ARPANET, the Precursor of the Internet, Created", 16) )
Deck.append( Game_Card(1969, "Neil Armstrong Becomes the First Man on the Moon", 17) )
Deck.append( Game_Card(1969, "Rock-and-Roll Concert at Woodstock", 18) )
Deck.append( Game_Card(1975, "Microsoft Founded", 19) )
Deck.append( Game_Card(1980, "John Lennon Assassinated", 20) )
Deck.append( Game_Card(1901, "First Nobel Prizes Awarded", 21) )
Deck.append( Game_Card(1905, "Einstein Proposes His Theory of Relativity", 22) )
Deck.append( Game_Card(1909, "Plastic Is Invented", 23) )
Deck.append( Game_Card(1912, "The Titanic Sinks", 24) )
Deck.append( Game_Card(1914, "World War I Begins", 25) )
Deck.append( Game_Card(1917, "Russian Revolution", 26) )
Deck.append( Game_Card(1922, "Insuline Discovered", 27) )
Deck.append( Game_Card(1924, "First Olympic Winter Games", 28) )
Deck.append( Game_Card(1930, "Gandhi's Salt March", 29) )
Deck.append( Game_Card(1939, "World War II Begins", 30) )
Deck.append( Game_Card(1921, "Irish Free State Is Established", 31) )
Deck.append( Game_Card(1932, "Franklin D. Roosevelt is Elected President of the United States", 32) )
Deck.append( Game_Card(1936, "Mussolini and Hitler signed the Rome-Berlin Axis.", 33) )
Deck.append( Game_Card(1902, "Cuba gains independence from the United States", 34) )
Deck.append( Game_Card(1932, "Duke Ellington writes It Don't Mean a Thing, If It Ain't Got That Swing", 35) )
Deck.append( Game_Card(1937, "Japanese invasion of China", 36) )
Deck.append( Game_Card(1903, "The Wright brothers invent the first gas motored and manned airplane", 37) )
Deck.append( Game_Card(1939, "Hewlett-Packard is Founded", 38) )
Deck.append( Game_Card(1919, "The flip-flop circuit invented", 39) )
Deck.append( Game_Card(1906, "William Kellogg Invents Cornflakes", 40) )
Deck.append( Game_Card(1935, "The world's first parking meter is installed in Oklahoma City", 41) )
Deck.append( Game_Card(1918, "The Allies win World War I", 42) )
Deck.append( Game_Card(1925, "Benito Mussolini Becomes the Dictator of Italy", 43) )
Deck.append( Game_Card(1918, "Influenza Virus Kills 20 Million People", 44) )
Deck.append( Game_Card(1923, "Heisenberg stated his uncertainty principle.", 45) )
Deck.append( Game_Card(1932, "Sir James Chadwick Discovers The Neutron.", 46) )
Deck.append( Game_Card(1900, "Friedrich Nietzsche dies", 47) )
Deck.append( Game_Card(1921, "Three Musicians by Picasso", 48) )
Deck.append( Game_Card(1929, "Lateran Treaty", 49) )
Deck.append( Game_Card(1924, "Oil Exploration Begins in Oman", 50) )
Deck.append( Game_Card(1930, "Pluto discovered", 51) )
Deck.append( Game_Card(1939, "Sigmund Freud dies", 52) )
Deck.append( Game_Card(1941, "Manhattan Project begins", 54) )
Deck.append( Game_Card(1936, "Spanish Civil War breaks out", 55) )
Deck.append( Game_Card(1937, "Guernica by Picasso", 56) )
Deck.append( Game_Card(1908, "First Model-T car produced by Ford", 57) )
Deck.append( Game_Card(1928, "Agriculture collectivized in USSR", 58) )
Deck.append( Game_Card(1932, "Iraq becomes an independent country", 59) )
Deck.append( Game_Card(1941, "Britain and US sign the Atlantic Charter", 60) )




